services:
  app:
    container_name: assistant-sagiri
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - gradle-cache:/home/gradle/.gradle
    restart: unless-stopped

volumes:
  gradle-cache:
