name: Codecov Upload

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: oURMIo/assistant-sagiri
