name: Gradle Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List files in app directory
        run: ls -la ./app

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Verify gradle installation
        run: ./app/gradlew --version

      - name: Build with Gradle
        run: ./app/gradlew clean build
