name: Gradle Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  PROJECT_DIR: ./app

defaults:
  run:
    working-directory: ${{ env.PROJECT_DIR }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew clean test
